# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: cypress/base:8

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
        # fallback to using the latest cache if no exact match is found

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        - ~/.npm
        - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

    - run:
        name: Launching App on localhost
        command: yarn run start
        background: true

    # run tests!
    - run:
        command: yarn test
        name: Running Unit Tests

    - run:
        command: yarn test:e2e
        name: Running E2E Test

    - store_artifacts:
        path: ./cypress/videos
        destination: ./videos

    - store_artifacts:
        path: ./cypress/screenshots
        destination: ./failures

